version: '3'
services:

  spark_server:
    container_name: spark_server
    build:
      context: .
      dockerfile: ./docker/server.dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
    environment:
      POSTGRES_DATABASE: shopping_cart
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: supersecret

  read_model_populator:
    container_name: read_model_populator
    build:
      context: .
      dockerfile: ./docker/rmp.dockerfile
    depends_on:
      - spark_server
    environment:
      POSTGRES_DATABASE: shopping_cart
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: supersecret
    restart: on-failure

  postgres_db:
    container_name: postgres_db
    build:
      context: .
      dockerfile: ./docker/postgres.dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: shopping_cart
      POSTGRES_PASSWORD: supersecret